apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-lab
data:
  APP_PORT: "8080"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RESPONSE_DELAY_MS: "0"
  ERROR_RATE: "0"
  FORCE_UNREADY: "false"
