apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels: {app: worker}
  template:
    metadata:
      labels: {app: worker}
    spec:
      containers:
        - name: worker
          image: devops-practice-lab:local
          imagePullPolicy: Never
          command: ["python", "-m", "src.worker"]
          envFrom: [{configMapRef: {name: app-config}}]
          resources:
            requests: {cpu: 10m, memory: 24Mi}
            limits: {cpu: 150m, memory: 96Mi}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
