global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: lab-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
